apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  annotations:
    iam.gke.io/gcp-service-account: prometheus@decisive-cinema-167507.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMServiceAccount
metadata:
  name: prometheus
  namespace: decisive-cinema-167507
spec:
  displayName: Prometheus Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: iampolicy-prometheus
  namespace: decisive-cinema-167507
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1alpha1
    kind: IAMServiceAccount
    name: prometheus
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:decisive-cinema-167507.svc.id.goog[default/prometheus]
---
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicyMember
metadata:
  name: prometheus-policy-metrics-writer
  namespace: decisive-cinema-167507
spec:
  member: serviceAccount:prometheus@decisive-cinema-167507.iam.gserviceaccount.com
  role: roles/monitoring.metricWriter
  resourceRef:
    kind: Project
    name: decisive-cinema-167507
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-global
  labels:
    prometheus: global
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-global
  labels:
    team: global
spec:
  selector:
    matchLabels:
      prometheus: global
  endpoints:
    - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  retention: 720h
  serviceMonitorSelector:
    matchLabels:
      team: global
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: prometheus
  version: v2.15.1
  serviceAccountName: prometheus
  # Temporary until we set up some kind of auth
  externalUrl: http://127.0.0.1:8001/api/v1/namespaces/default/services/prometheus-global:web/proxy/
  resources:
    requests:
      memory: 400Mi
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 40Gi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: prometheus-config-reloader
    resources:
      requests:
        cpu: 5m
  - name: rules-configmap-reloader
    resources:
      requests:
        cpu: 5m
