apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: isaacranks
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: isaacranks-prod-db-credentials
                  key: username
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: isaacranks-prod-db-credentials
                  key: password
            - name: PGDATABASE
              value: isaacranks_prod
            - name: BALLOT_MASKING_KEY
              valueFrom:
                secretKeyRef:
                  name: isaacranks-prod-isaacranks
                  key: ballot-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebuild
spec:
  template:
    spec:
      containers:
        - name: rebuildranks
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: isaacranks-prod-db-credentials
                  key: username
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: isaacranks-prod-db-credentials
                  key: password
            - name: PGDATABASE
              value: isaacranks_prod
            - name: BALLOT_MASKING_KEY
              valueFrom:
                secretKeyRef:
                  name: isaacranks-prod-isaacranks
                  key: ballot-key
