apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ucdapi-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ucdapi
    spec:
      containers:
        - name: ucdapi
          image: eu.gcr.io/decisive-cinema-167507/ucdapi:6e0c3e5
          ports:
            - containerPort: 3000
          env:
            - name: APPROOT
              value: 'https://ucdapi.org'
            - name: IP_FROM_HEADER
              value: 'true'
          resources:
            requests:
              cpu: '10m'
              memory: '100Mi'
