apiVersion: v1
kind: Service
metadata:
  name: ucdapi
  labels:
    app: ucdapi
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: ucdapi
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: ucdapi
  labels:
    team: global
spec:
  selector:
    matchLabels:
      app: ucdapi
  endpoints:
    - port: web
