apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: global
  version: v1.7.1
  resources:
    requests:
      memory: 400Mi
  storage:
    resources:
      requests:
        storage: 40Gi
