---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.5.15
          imagePullPolicy: IfNotPresent
          args:
            - -m 64    # Maximum memory to use, in megabytes. 64MB is default.
            - -I 5m    # Maximum size for one item
            - -p 11211 # Default port
          resources:
            requests:
              cpu: "5m"
              memory: "64Mi"
            limits:
              memory: "64Mi"
          ports:
            - name: clients
              containerPort: 11211
          securityContext:
            runAsUser: 11211
            runAsGroup: 11211
            allowPrivilegeEscalation: false
