apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambdacircus-deployment
  labels:
    app: lambdacircus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lambdacircus
  template:
    metadata:
      labels:
        app: lambdacircus
    spec:
      containers:
        - name: lambdacircus
          image: eu.gcr.io/decisive-cinema-167507/lambdacircus:d531b2e
          ports:
            - containerPort: 3000
          env:
            - name: APPROOT
              value: 'https://qdb.codehash.net'
            - name: IP_FROM_HEADER
              value: 'true'
            - name: PGHOST
              value: 172.30.16.3
            - name: PGPORT
              value: '5432'
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: lambdacircus-db-credentials
                  key: username
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: lambdacircus-db-credentials
                  key: password
            - name: PGDATABASE
              value: 'lambdacircus'
            - name: LAMBDACIRCUS_CLIENT_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: lambdacircus-client-session-key
                  key: key
          resources:
            requests:
              cpu: "10m"
