apiVersion: v1
kind: Service
metadata:
  name: lambdacircus
  labels:
    app: lambdacircus
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: lambdacircus
