apiVersion: v1
kind: Service
metadata:
  name: lambdacircus
  labels:
    app: lambdacircus
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"standard"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: lambdacircus
