apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucdapi-deployment
  labels:
    app: ucdapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ucdapi
  template:
    metadata:
      labels:
        app: ucdapi
    spec:
      containers:
        - name: ucdapi
          image: eu.gcr.io/decisive-cinema-167507/ucdapi:873e287
          ports:
            - containerPort: 3000
          env:
            - name: APPROOT
              value: 'https://ucdapi.org'
            - name: IP_FROM_HEADER
              value: 'true'
          resources:
            requests:
              cpu: '10m'
              memory: '100Mi'
