---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  name: test-isaacranks-rebuild
  namespace: default
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: rebuildranks
      containers:
      - image: eu.gcr.io/decisive-cinema-167507/isaacranks:git-df8a5a67934ab010d4389a50849147e18cbae0f9
        name: rebuildranks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  name: test-isaacranks-web
  namespace: default
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: isaacranks
      containers:
      - image: eu.gcr.io/decisive-cinema-167507/isaacranks:git-df8a5a67934ab010d4389a50849147e18cbae0f9
        name: isaacranks
