apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeAddress
metadata:
  name: global-ingress
  namespace: decisive-cinema-167507
spec:
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeAddress
metadata:
  name: global-ingress-v6
  namespace: decisive-cinema-167507
spec:
  location: global
  ipVersion: IPV6
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: global-ingress
  annotations:
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.global-static-ip-name: 'global-ingress'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - ucdapi.org
  #       - graphs.mithrandi.net
      secretName: acme-tls
    - hosts:
        - pb.codehash.net
      secretName: acme-tls-pbc
    - hosts:
        - qdb.codehash.net
      secretName: acme-tls-qdb
    - hosts:
        - test.isaacranks.com
      secretName: acme-tls-ir-test
    - hosts:
        - www.isaacranks.com
      secretName: acme-tls-ir-prod
  rules:
    - host: ucdapi.org
      http:
        paths:
          - backend:
              serviceName: ucdapi
              servicePort: 80
    - host: pb.codehash.net
      http:
        paths:
          - backend:
              serviceName: codetip
              servicePort: 80
    - host: qdb.codehash.net
      http:
        paths:
          - backend:
              serviceName: lambdacircus
              servicePort: 80
    # - host: graphs.mithrandi.net
    #   http:
    #     paths:
    #       - backend:
    #           serviceName: grafana
    #           servicePort: web
    - host: test.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: test-isaacranks-web
              servicePort: web
    - host: www.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: prod-isaacranks-web
              servicePort: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: global-ingress6
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 'global-ingress-v6'
    kubernetes.io/ingress.class: 'gce'
spec:
  tls:
    - hosts:
        - ucdapi.org
      secretName: acme-tls
    - hosts:
        - pb.codehash.net
      secretName: acme-tls-pbc
    - hosts:
        - qdb.codehash.net
      secretName: acme-tls-qdb
    - hosts:
        - test.isaacranks.com
      secretName: acme-tls-ir-test
    - hosts:
        - www.isaacranks.com
      secretName: acme-tls-ir-prod
  rules:
    - host: ucdapi.org
      http:
        paths:
          - backend:
              serviceName: ucdapi
              servicePort: 80
    - host: pb.codehash.net
      http:
        paths:
          - backend:
              serviceName: codetip
              servicePort: 80
    - host: qdb.codehash.net
      http:
        paths:
          - backend:
              serviceName: lambdacircus
              servicePort: 80
    # - host: graphs.mithrandi.net
    #   http:
    #     paths:
    #       - backend:
    #           serviceName: grafana
    #           servicePort: web
    - host: test.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: test-isaacranks-web
              servicePort: web
    - host: www.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: prod-isaacranks-web
              servicePort: web
