apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: global-ingress
  annotations:
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.global-static-ip-name: 'k8s-fw-default-global-ingress--6928bd11e243f349'
spec:
  tls:
    - hosts:
        - ucdapi.org
        - pb.codehash.net
        - qdb.codehash.net
        - graphs.mithrandi.net
        - test.isaacranks.com
        - www.isaacranks.com
      secretName: acme-tls
  rules:
    - host: ucdapi.org
      http:
        paths:
          - backend:
              serviceName: ucdapi
              servicePort: 80
    - host: pb.codehash.net
      http:
        paths:
          - backend:
              serviceName: codetip
              servicePort: 80
    - host: qdb.codehash.net
      http:
        paths:
          - backend:
              serviceName: lambdacircus
              servicePort: 80
    - host: graphs.mithrandi.net
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: web
    - host: test.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: isaacranks-test-isaacranks
              servicePort: web
    - host: www.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: isaacranks-prod-isaacranks
              servicePort: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: global-ingress6
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 'lbv6'
    kubernetes.io/ingress.class: 'gce'
spec:
  tls:
    - hosts:
        - ucdapi.org
        - pb.codehash.net
        - qdb.codehash.net
        - graphs.mithrandi.net
        - test.isaacranks.com
        - www.isaacranks.com
      secretName: acme-tls
  rules:
    - host: ucdapi.org
      http:
        paths:
          - backend:
              serviceName: ucdapi
              servicePort: 80
    - host: pb.codehash.net
      http:
        paths:
          - backend:
              serviceName: codetip
              servicePort: 80
    - host: qdb.codehash.net
      http:
        paths:
          - backend:
              serviceName: lambdacircus
              servicePort: 80
    - host: graphs.mithrandi.net
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: web
    - host: test.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: isaacranks-test-isaacranks
              servicePort: web
    - host: www.isaacranks.com
      http:
        paths:
          - backend:
              serviceName: isaacranks-prod-isaacranks
              servicePort: web
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: default
spec:
  secretName: acme-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mithrandi.net
  dnsNames:
    - ucdapi.org
    - pb.codehash.net
    - qdb.codehash.net
    - graphs.mithrandi.net
    - test.isaacranks.com
    - www.isaacranks.com
  acme:
    config:
      - dns01:
          provider: prod-route53
        domains:
          - mithrandi.net
          - ucdapi.org
          - pb.codehash.net
          - qdb.codehash.net
          - graphs.mithrandi.net
          - test.isaacranks.com
          - www.isaacranks.com
