apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: mithrandi@mithrandi.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    dns01:
      providers:
      - name: prod-route53
        route53:
          region: eu-west-1
          accessKeyID: AKIAJT4RLSNEPWK74BGA
          secretAccessKeySecretRef:
            name: kcm-route53-credentials
            key: secret
