apiVersion: v1
kind: Service
metadata:
  name: rebuild
  labels:
    component: rebuild
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    component: rebuild
