apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebuild
  labels:
    component: rebuild
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rebuild
  template:
    metadata:
      labels:
        component: rebuild
    spec:
      containers:
        - name: rebuildranks
          image: eu.gcr.io/decisive-cinema-167507/isaacranks:1.0.10
          command: ["/usr/local/bin/rebuildranks"]
          args: ["300"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: 172.30.16.3
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: isaacranks-db-credentials
                  key: username
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: isaacranks-db-credentials
                  key: password
            - name: PGDATABASE
              value: isaacranks
            - name: BALLOT_MASKING_KEY
              valueFrom:
                secretKeyRef:
                  name: isaacranks
                  key: ballot-key
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3000
