apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  labels:
    team: global
    component: web
spec:
  selector:
    matchLabels:
      component: web
  endpoints:
    - port: web
