apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    component: web
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"standard"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    component: web
