apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    component: web
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    component: web
