apiVersion: apps/v1
kind: Deployment
metadata:
  name: codetip-deployment
  labels:
    app: codetip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codetip
  template:
    metadata:
      labels:
        app: codetip
    spec:
      containers:
        - name: codetip
          image: eu.gcr.io/decisive-cinema-167507/codetip:ea41fef
          args:
            - '--database-uri'
            - 'jdbc:postgresql://172.30.16.3:5432/codetip?user=$(DB_USER)&password=$(DB_PASS)'
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: codetip-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: codetip-db-credentials
                  key: password
          resources:
            requests:
              cpu: "10m"
