apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: grafana
        image: grafana/grafana:6.5.2
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_GITHUB_ENABLED
          value: 'true'
        - name: GF_AUTH_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: grafana-github
              key: id
        - name: GF_AUTH_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: grafana-github
              key: secret
        - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
          value: 'false'
        - name: GF_USER_ALLOW_SIGN_UP
          value: 'false'
        - name: GF_USER_ALLOW_ORG_CREATE
          value: 'false'
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: password
        - name: GF_SERVER_DOMAIN
          value: 'graphs.mithrandi.net'
        - name: GF_SERVER_ROOT_URL
          value: 'https://graphs.mithrandi.net/'
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/grafana-storage
        - name: grafana-dashboards
          mountPath: /var/grafana-dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-sources
          mountPath: /etc/grafana/provisioning/dashboards
        ports:
        - name: web
          containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 200Mi
            cpu: 200m
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-sources
        configMap:
          name: grafana-dashboard-sources
