apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- svc.yaml
commonLabels:
  app: grafana
configMapGenerator:
- name: grafana-dashboards
  files:
  - isaacranks-prod.dashboard.json
  - isaacranks-test.dashboard.json
  - ucdapi.dashboard.json
- name: grafana-datasources
  files:
    - prometheus.yaml
- name: grafana-dashboard-sources
  files:
    - dashboards.yaml
