apiVersion: v1
kind: Secret
metadata:
  name: {{ template "isaacranks.fullname" . }}
  labels:
    app: {{ template "isaacranks.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ballot-key: {{ required "Must provide ballotKey; generate with head -c 96 /dev/urandom | base64 -w0" .Values.ballotKey | b64enc | quote }}
