apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: eridanus
spec:
  serviceName: eridanus
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eridanus
    spec:
      containers:
        - name: eridanus
          image: eu.gcr.io/decisive-cinema-167507/eridanus:11c80c7024548ce7c41800b077d3d0a738a04875
          volumeMounts:
            - name: eridanus-data
              mountPath: /db
  volumeClaimTemplates:
    - metadata:
        name: eridanus-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100M
